# Generated by Django 3.0.8 on 2020-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='date_modified',
            field=models.CharField(max_length=100),
        ),
    ]
