# Generated by Django 3.0.8 on 2020-07-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_app', '0003_pump'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
