# Generated by Django 3.0.8 on 2020-07-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink_app', '0006_auto_20200726_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute1',
            new_name='substitute1',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute2',
            new_name='substitute2',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute3',
            new_name='substitute3',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute4',
            new_name='substitute4',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute5',
            new_name='substitute5',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute6',
            new_name='substitute6',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute7',
            new_name='substitute7',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='subsitute8',
            new_name='substitute8',
        ),
    ]
